---
title: "From R/RStudio to GitHub"
author: "Jenny Bryan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{From R/RStudio to GitHub}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Current situation

If your goal is to have a project that is:

  * a directory on your computer
  * an RStudio Project
  * a Git repository
  * associated with a remote repository on GitHub

How can you achieve this?

__GitHub First__: This is the workflow [we recommend in STAT 545](http://stat545-ubc.github.io/git07_git-github-rstudio.html), because it does not require going to the shell or explicit use of command line Git. Main steps:

  * *Prerequisite: Install Git. Git global config. Make sure RStudio has found Git executable.*
  * New repo on GitHub.YES to README. URL --> clipboard.
  * In RStudio: *File > New Project > Version Control > Git*.
  
Why is this good for "my first repo"?

  * Easy to explain: not OS specific, never go to shell.
  * Based on clicking in RStudio or a browser: doesn't require 100% typing accuracy.
  * GitHub repo is set up as a remote for local repo.
  * Local master is tracking `origin/master`, so push and pull work immediately. In particular, the push and pull buttons in RStudio work.

What are the downsides?

  * Requires system installation of Git and for RStudio to know where it is.
  * Must happen at the start of a project.
  * Based on clicking in RStudio or a browser, so must document with lots of words and screenshots versus R code.

__RStudio First__: This is what we call [Plan B workflow in STAT 545](http://stat545-ubc.github.io/git07_git-github-rstudio.html). Main steps:

  * *Prerequisite: Install Git. Git global config. Make sure RStudio has found Git executable.*
  * In RStudio: *File > New Project > New Directory > Empty Project*.
    - Either at project start, say YES to "Create a git repository", or do so later with *Tools > Version Control > Project Setup > Version control system: Git,* YES init a repo, YES restart RStudio.
    - Do some work. Realize you want this thing on GitHub.
  * New repo on GitHub. URL --> clipboard or otherwise note it.
  * In shell, with wd in the repo, add GitHub repo as remote via `git remote add`.
  * In shell, pull if there's anything you need on GitHub, such as a README or LICENSE.
  * In shell, `git push -u origin master` to set upstream tracking.

What are the downsides?

  * Requires system installation of Git and for RStudio to know where it is.
  * Requires cycling through RStudio, shell, and GitHub in the browser. Hard to write up as a lesson and students hate this in live demo, i.e. people get lost.
  
### Near term goals

Delay Git installation + RStudio/Git handshake: I can't imagine anyone doing lots of Git work w/o installing Git on their system, i.e. *only* using what's exposed in `git2r` or `githug`. But we could hope to make this unnecessary for the first few hours or days.

Git config: DONE.

Git init in Project: DONE.

Emulate `hub create jennybc/foo`. DONE.

  - init local repo, if not done already
  - add and commit
  - create new GitHub repo
  - add as remote
  - push the current branch
  - visit GitHub repo in the browser
